# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

# Install dependencies including devDependencies (for build)
RUN npm install

# Copy rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose ports if needed (uncomment if the MCP has network exposure, normally uses stdio)

# Start the MCP server
CMD ["node", "build/index.js"]
